### ISSUE TITLE
How difficult would it be to add support for p6-GtkPlus?

### ISSUE THREAD

**Issue by Xliff** [CIAvash/GtkLayerShell#1]
If you need a link to the project, you can find it [here](http://github.com/Xliff/p6-GtkPlus). I wouldn't mind doing a lion share of the work if you could communicate the high level strategy of your design.

Thanks!

**Comment by CIAvash** [comment]
I wasn't aware of your module, it hasn't been released yet?

I didn't add support for other libraries, all you need is a `Pointer` to window widget, or monitor if you want to use a method that works with monitor.

For example, for Gnome::Gtk3, it's `$gtk_window.get-native-object` for GTK::Simple, it's `$app.WIDGET`. And from having a quick look at your module, it's `$gtk_window.widget` along with some other aliases? So if I'm not mistaken, in short it would be:
```raku
use GTK::Window;

my GTK::Window $gtk_window .= new: GTK_WINDOW_TOPLEVEL;

my $window = $gtk_window.widget;

my GtkLayerShell $layer_surface .= new: :$window, :init;
```

**Comment by Xliff** [comment]
@CIAvash, No. These have not been released yet. Mainly because it became quite large, quite quickly. 

I'm glad to see your module is fairly agnostic in its approach. Thanks for writing it.
